[package]
name = "slot_core"
version = "0.1.0"
edition = "2021"
build = "build.rs"
publish = false

[lib]
name = "slot_core"
crate-type = ["cdylib", "rlib"]

[dependencies]
chacha20poly1305 = "0.10"
getrandom = "0.2"

[build-dependencies]
chacha20poly1305 = "0.10"
getrandom = "0.2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
