"""Builds rust/slot_core/math/model.txt from symbol counts per reel.

Only a tuning aid: the generated text file is consumed by build.rs, which
encrypts it. Re-run, then `cargo test --release simulate -- --ignored --nocapture`.
"""
import random

COUNTS = [
    # TEN J  Q  K  A  CHR BEL BAR DIA CHP CRN COIN WILD BON
    [6, 6, 6, 5, 5, 5, 4, 4, 3, 2, 1, 1, 0, 1],
    [6, 6, 5, 5, 5, 4, 4, 4, 3, 2, 2, 1, 2, 1],
    [5, 5, 5, 5, 5, 4, 4, 4, 3, 3, 2, 2, 2, 2],
    [6, 5, 5, 5, 5, 4, 4, 4, 3, 2, 2, 1, 2, 1],
    [6, 6, 6, 5, 5, 5, 4, 4, 3, 2, 1, 1, 0, 1],
]
import os
if os.environ.get("AZ_TEST_BONUS"):
    # Visual testing only: make the feature and wilds show up constantly.
    for row in COUNTS:
        row[13] = 9
        if row[12]:
            row[12] = 8
NAMES = ["TEN", "J", "Q", "K", "A", "CHERRY", "BELL", "BAR", "DIAMOND",
         "CHIPS", "CROWN", "COIN", "WILD", "BONUS"]

# per way, thousandths of the total bet, for 3 / 4 / 5 of a kind
PAYS = {
    "TEN": (4, 12, 40), "J": (4, 12, 40), "Q": (5, 15, 50), "K": (5, 15, 50),
    "A": (6, 18, 60), "CHERRY": (8, 24, 80), "BELL": (10, 30, 100),
    "BAR": (12, 40, 120), "DIAMOND": (16, 50, 160), "CHIPS": (20, 70, 220),
    "CROWN": (30, 100, 320), "COIN": (50, 160, 500),
}
PAY_SCALE = 26.0
SCATTER_PAY = (2000, 5000, 20000)
FREE_SPINS = (8, 12, 20)
FREE_MULT = 2


def strip(counts, seed):
    rng = random.Random(seed)
    items = [i for i, c in enumerate(counts) for _ in range(c)]
    for _ in range(5000):
        rng.shuffle(items)
        n = len(items)
        if all(items[i] != items[(i + 1) % n] for i in range(n)):
            return items
    raise SystemExit("could not place strip without neighbours")


lines = ["# Generated by tool/gen_model.py. Never shipped; build.rs encrypts it."]
for i, c in enumerate(COUNTS):
    lines.append(f"reel{i + 1} = " + " ".join(NAMES[s] for s in strip(c, 1000 + i)))
for name, p in PAYS.items():
    scaled = [round(v * PAY_SCALE) for v in p]
    lines.append(f"pay {name} = {scaled[0]} {scaled[1]} {scaled[2]}")
lines.append("scatter_pay = %d %d %d" % SCATTER_PAY)
lines.append("free_spins = %d %d %d" % FREE_SPINS)
lines.append(f"free_multiplier = {FREE_MULT}")

import os
path = os.path.join(os.path.dirname(__file__), "..", "rust", "slot_core", "math", "model.txt")
os.makedirs(os.path.dirname(path), exist_ok=True)
open(path, "w", encoding="utf-8").write("\n".join(lines) + "\n")
print("written", os.path.normpath(path))

